site_name: VivaWiki
site_description: 개인 백엔드 학습 위키
site_url: https://vivatubeh.github.io/VivaWiki/

theme:
  name: material
  language: ko
  font:
    text: Noto Sans KR
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: false
      line_spans: __span
      pygments_lang_class: true


nav:
  - 홈: index.md

  - CS 기초:
      - Index: CS 기초/index.md
      - 네트워크:
          - Index: CS 기초/네트워크/index.md
      - 운영체제:
          - Index: CS 기초/운영체제/index.md
          - 사용자 모드 vs 커널 모드: CS 기초/운영체제/운영체제의 사용자 모드 vs 커널 모드.md
      - 컴퓨터구조:
          - Index: CS 기초/컴퓨터구조/index.md
      - 자료구조 & 알고리즘:
          - Index: CS 기초/자료구조 & 알고리즘/index.md
      - 데이터베이스:
          - Index: CS 기초/데이터베이스/index.md
          - SQL:
              - Index: CS 기초/데이터베이스/SQL/index.md
          - 설계 & 최적화:
              - Index: CS 기초/데이터베이스/설계 & 최적화/index.md
          - 트랜잭션 & 동시성:
              - Index: CS 기초/데이터베이스/트랜잭션 & 동시성/index.md

  - Java:
      - Index: Java/index.md

  - Spring:
      - Index: Spring/index.md
      - Spring 이론:
          - Index: Spring/Spring 이론/index.md
      - Spring 구현:
          - Index: Spring/Spring 구현/index.md
      - JPA & ORM:
          - Index: Spring/JPA & ORM/index.md
      - 보안:
          - Index: Spring/보안/index.md
      - 테스팅:
          - Index: Spring/테스팅/index.md
      - 로깅:
          - Index: Spring/로깅/index.md

  - 프론트엔드:
      - Index: 프론트엔드/index.md
      - HTML:
          - Index: 프론트엔드/HTML/index.md
      - CSS:
          - Index: 프론트엔드/CSS/index.md
      - JavaScript:
          - Index: 프론트엔드/JavaScript/index.md
      - 비동기 처리:
          - Index: 프론트엔드/비동기 처리/index.md
      - 서버 템플릿 엔진:
          - Index: 프론트엔드/서버 템플릿 엔진/index.md
      - 프론트엔드 라이브러리:
          - Index: 프론트엔드/프론트엔드 라이브러리/index.md

  - 개발도구:
      - Index: 개발도구/index.md
      - 버전 관리 Git & Github:
          - Index: 개발도구/버전 관리 Git & Github/index.md
      - 빌드 도구:
          - Index: 개발도구/빌드 도구/index.md
      - 인프라 & DevOps:
          - Index: 개발도구/인프라 & DevOps/index.md
      - IntelliJ:
          - Index: 개발도구/IntelliJ/index.md

  - 아키텍처 & 설계:
      - Index: 아키텍처 & 설계/index.md
